---
title: "DADA2 Pipeline"
author: "Fateema Bazzi"
date: "2026-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Include Libraries and Set Working Directory

```{r, echo=FALSE}
setwd(this.path::here())
library(dada2)
```

## Data Retrieval

```{r}
path <- "../data/raw_fastq/unzipped" # directory containing the unzipped fastq files.
list.files(path)
fastqs <- sort(list.files(path,  pattern=".fastq", full.names = TRUE))
# Extract sample names
sample.names <- sapply(strsplit(basename(fastqs), "\\."), `[`, 1)
```

## Read Quality Profiles

```{r}
plotQualityProfile(fastqs[1:2])
```

## Filter and Trim

```{r}
# Place filtered files in filtered/ subdirectory
filts <- file.path(path, "filtered", paste0(sample.names, "_filt.fastq.gz"))
names(filts) <- sample.names

#trunclen determined by previous multiqc and quality profile
#TODO : play w maxEE and trunclen
out <- filterAndTrim(fastqs, filts, truncLen=c(250),
              maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
              compress=TRUE) 
head(out)
```

## Learn the Error Rates

```{r}
err <- learnErrors(filts)
```
```{r}
#visualize estimated error rates
plotErrors(err, nominalQ=TRUE)
```

## Sample Inference
```{r}
dadas <- dada(filts, err=err)
dadas[[1]]
```

## Construct Sequence Table

```{r}
seqtab <- makeSequenceTable(dadas)
dim(seqtab)
```
```{r}
# Inspect distribution of sequence lengths
table(nchar(getSequences(seqtab)))
```

## Remove Chimeras
```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", verbose=TRUE)
dim(seqtab.nochim)
#proportion on nonchimera reads
sum(seqtab.nochim)/sum(seqtab)
```

## Track Reads Through the Pipeline

```{r}
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadas, getN), rowSums(seqtab.nochim))

colnames(track) <- c("input", "filtered", "denoised", "nonchim")
rownames(track) <- sample.names
head(track)
```

## Assign Taxonomy
I use the RDP reference database, to match what was used by the original authors.