---
title: "Differential Abundance"
author: "Fateema Bazzi"
date: "2026-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load in Libraries and Set Working Directory

```{r, include=FALSE}
setwd(this.path::here())

library(tidyverse)
library(phyloseq)
library(ggplot2)
library(ANCOMBC)
library(microbiome)
library(RColorBrewer)
library(ggrepel)
library(pheatmap)
```

## Load in Data

```{r}
physeq <- readRDS("../results/phylogeny/phyloseq.rds")
```

## Create Genus-Level Object

```{r}
physeq_genus <- tax_glom(
    physeq,
    taxrank = "Genus"
)
#check how many taxa remain
ntaxa(physeq_genus) #down from 2173
#handle unknowns
taxa_names(physeq_genus)[is.na(taxa_names(physeq_genus))] <- "Unclassified"
```

## ANCOM-BC

```{r}
#set control group
sample_data(physeq_genus)$Group <- relevel(
    sample_data(physeq_genus)$Group,
    ref="EU"
)

#preserve taxon names
taxa_names(physeq_genus) <- paste0(
    "Genus_",
    seq_len(ntaxa(physeq_genus))
)
tax_map <- data.frame(
    Taxon_ID = taxa_names(physeq_genus),
    as.data.frame(tax_table(physeq_genus))
)

da_results <- ancombc(
    data = physeq_genus,
    formula = "Group",
    p_adj_method = "BH" #multiple testing correction
)
```
Extract Log FC and Q-Vals
```{r}
lfc <- da_results$res$lfc
qvals <- da_results$res$q_val
```

## Differential Abundance Table
```{r}
da_table <- data.frame(
    Taxon_ID = rownames(da_results$feature_table),
    logFC = da_results$res$lfc[, "GroupBF"],
    p_value = da_results$res$p_val[, "GroupBF"],
    q_value = da_results$res$q_val[, "GroupBF"]
)

#add significance indication
da_table$Significant <- 
    da_table$q_value < 0.05 &
    abs(da_table$logFC) > 1

#add direction of differential abundance
da_table$Direction <- "Not Sig" #if direction is not significant
# if log2Foldchange > 1 and qvalue < 0.05, set as "BF enriched" 
da_table$Direction[da_table$logFC > 1 & da_table$q_value < 0.05] <- "BF enriched"
# if log2Foldchange < -1 and qvalue < 0.05, set as "EU enriched"
da_table$Direction[da_table$logFC < -1 & da_table$q_value < 0.05] <- "EU enriched"

# add taxonomy info
tax_df <- as.data.frame(tax_table(physeq_genus))
tax_df$Taxon_ID <- rownames(tax_df)

da_table <- merge(
    da_table,
    tax_df,
    by = "Taxon_ID",
    all.x = TRUE
)

#add taxon column
da_table$Taxon <- da_table$Genus

#reorder
da_table <- da_table[, c(
    "Taxon",
    "Phylum",
    "Class",
    "Order",
    "Family",
    "Genus",
    "logFC",
    "p_value",
    "q_value",
    "Significant",
    "Direction",
    "Taxon_ID"
)]

head(da_table)
```

## Visualize
Volcano Plot
```{r}
#add row to conditionally label the taxons
da_table$TaxonLabel <- NA
da_table$TaxonLabel[da_table$Direction != "Not Sig"] <- da_table$Taxon[da_table$Direction != "Not Sig"]

#Plot
diff_abund_volcano <- ggplot(data = da_table, aes(x = logFC, y = -log10(q_value), col = Direction, label=TaxonLabel)) +
   geom_point() + 
  theme_minimal() +
  geom_label_repel(size=6) +
  scale_color_manual(values = c("blue", "black", "red")) +
  geom_vline(xintercept=c(-1, 1), col="gray") +
  geom_hline(yintercept=-log10(0.05), col="gray") +
  theme(legend.position = "none",
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 15))
diff_abund_volcano
```

Heat Map
```{r}
#grab sig taxa
sig_taxa <- da_table$Taxon_ID[da_table$Significant]
#subset physeq_genus to only include sig
physeq_sig <- prune_taxa(sig_taxa, physeq_genus)
#transform to relative abund
physeq_sig_rel <- transform_sample_counts(physeq_sig, function(x) x / sum(x))
#extract abund mat
abund_mat <- as(otu_table(physeq_sig_rel), "matrix")
abund_mat <- t(abund_mat) #transpose to make rows taxa
#label rows w genus names
rownames(abund_mat) <- da_table$Taxon[match(rownames(abund_mat), da_table$Taxon_ID)]
#add sample annotations
sample_annotation <- data.frame(
    Group = sample_data(physeq_sig_rel)$Group
)
rownames(sample_annotation) <- sample_names(physeq_sig_rel)

abund_heatmap <- pheatmap(
    abund_mat,
    scale = "row",
    annotation_col = sample_annotation,
    fontsize_row = 15, 
    fontsize_col = 12,
    main = "Taxon Abundance Per Sample"
)
abund_heatmap
```

Bar Plot
```{r}
#filter table to only sig
da_sig <- subset(da_table, Significant)
#order by abs(logfc)
da_sig <- da_sig[order(abs(da_sig$logFC), decreasing = TRUE), ]
diff_abund_barplot <- ggplot(da_sig,aes(x = reorder(Taxon, logFC), y = logFC, fill = Direction)) +
    geom_col() +
    coord_flip() +
    labs(
        x = "Genus",
        y = "Log Fold Change",
        title = "Differentially Abundant Genera"
    ) +
  theme(axis.title = element_text(size = 25),
        axis.text = element_text(size = 20),
        plot.title = element_text(size=25)) +
    theme_minimal()
diff_abund_barplot
```

## Save Results
```{r}
#differential abundance table
saveRDS(da_table, "../results/differential_abundance/diff_abund_tbl.rds")
write.csv(da_table, "../results/differential_abundance/diff_abund_tbl.csv")
#visuals
ggsave("../results/differential_abundance/diff_abund_volcano.png", plot = diff_abund_volcano,width = 12, height = 10, units = "in")
ggsave("../results/differential_abundance/abund_heatmap.png", plot = abund_heatmap, width = 12, height = 10, units = "in")
ggsave("../results/differential_abundance/diff_abund_barplot.png", plot = diff_abund_barplot, width = 12, height = 10, units = "in")
```